apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: loan_approval_db
  POSTGRES_USER: testdevusername
  POSTGRES_PASSWORD: testdevpassword